# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xcvu065-ffvc1517-1-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/AUC/Arch/Arch-Lab/project_2/project_2.cache/wt [current_project]
set_property parent.project_path E:/AUC/Arch/Arch-Lab/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/AUC/Arch/Arch-Lab/project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab04/Lab04/Lab04.srcs/sources_1/new/ALU.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab04/Lab04/Lab04.srcs/sources_1/new/ALUcu.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/new/BCD.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab03/Lab03.srcs/sources_1/new/DFlipFlop.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab05/Lab05/Lab05.srcs/sources_1/new/DataMem.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/new/F_Dig_7_dig.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab04/Lab04/Lab04.srcs/sources_1/imports/new/Full_Adder.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab03/Lab03.srcs/sources_1/new/ImmGen.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab05/Lab05/Lab05.srcs/sources_1/new/InstMem.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab04/Lab04/Lab04.srcs/sources_1/imports/Desktop/Lab03/Lab03.srcs/sources_1/new/Mux2x1.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab04/Lab04/Lab04.srcs/sources_1/new/cu.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab04/Lab04/Lab04.srcs/sources_1/imports/new/mMuxes.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab04/Lab04/Lab04.srcs/sources_1/new/mux16x1.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab03/Lab03.srcs/sources_1/new/nBitRegister.v
  {E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab04/Lab04/Lab04.srcs/sources_1/imports/Desktop/Lab 2/Lab 2.srcs/sources_1/new/n_bit_RCA.v}
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab04/Lab04/Lab04.srcs/sources_1/new/regFile.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/Desktop/Lab03/Lab03.srcs/sources_1/new/sl1.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/new/TOP.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/new/rising_edge_detector.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/new/debouncer.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/new/synchronizer.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/new/push_button_detector.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/new/RISCV_pipeline.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/VerilogSrc/prv32_ALU.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/VerilogSrc/ImmGen.v
  E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/sources_1/imports/VerilogSrc/defines.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/constrs_1/new/TOP_const.xdc
set_property used_in_implementation false [get_files E:/AUC/Arch/Arch-Lab/project_2/project_2.srcs/constrs_1/new/TOP_const.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top RISCV_pipeline -part xcvu065-ffvc1517-1-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RISCV_pipeline.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RISCV_pipeline_utilization_synth.rpt -pb RISCV_pipeline_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
